language: python
addons:
  firefox: "52.0.2"
sudo: true
python: 2.7
cache:
  directories:
    - buildout-cache
install:
  - mkdir -p buildout-cache/downloads
  - pip install -r requirements.txt
  - buildout -c travis.cfg -N
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - firefox -v
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.15.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage --output-dir htmlcov
  - pip install -q coveralls==0.5
  - coveralls
notifications:
  email:
    recipients:
      - devel@lists.affinitic.be
      - devs@imio.be
    on_success: change
    on_failure: change
  irc:
    channels:
      - "irc.freenode.org#imio"
    on_success: change
    on_failure: always
